#!/bin/bash

# Create Docker Compose file from base64 encoded string
echo "dmVyc2lvbjogJzMnCnNlcnZpY2VzOgogIHdpcmVndWFyZDoKICAgIGltYWdlOiBsaW51eHNlcnZlci93aXJlZ3VhcmQKICAgIGNvbnRhaW5lcl9uYW1lOiB3aXJlZ3VhcmQKICAgIGNhcF9hZGQ6CiAgICAgIC0gTkVUX0FETUlOCiAgICAgIC0gU1lTX01PRFVMRQogICAgZW52aXJvbm1lbnQ6CiAgICAgIC0gUFVJRD0xMDAwCiAgICAgIC0gUEdJRD0xMDAwCiAgICAgIC0gVFo9RXVyb3BlL0xvbmRvbgogICAgICAtIFNFUlZFUlVSTD1hdXRvCiAgICAgIC0gU0VSVkVSUE9SVD01MTgyMAogICAgICAtIFBFUVJTPTEwCiAgICBwb3J0czoKICAgICAgLSA1MTgyMDo1MTgyMC91ZHAKICAgIHZvbHVtZXM6CiAgICAgIC0gLi93aXJlZ3VhcmRfY29uZmlnOi9jb25maWcKICAgIHJlc3RhcnQ6IHVubGVzcy1zdG9wcGVkCiAgICBuZXR3b3JrczoKICAgICAgLSBteV9uZXR3b3JrCgogIG15c3FsOgogICAgaW1hZ2U6IG15c3FsOmxhdGVzdAogICAgY29udGFpbmVyX25hbWU6IG15c3FsCiAgICBlbnZpcm9ubWVudDoKICAgICAgLSBNU1FMX1JPT1RfUEFTU1dPUkQ9cm9vdAogICAgbmV0d29ya3M6CiAgICAgIC0gbXlfbmV0d29yawoKICBtYWlsOgogICAgaW1hZ2U6IG1haWxzZXJ2ZXIvZG9ja2VyLW1haWxzZXJ2ZXI6bGF0ZXN0CiAgICBob3N0bmFtZTogbWFpbAogICAgZG9tYWlubmFtZTogd2cKICAgIGNvbnRhaW5lcl9uYW1lOiBtYWlsCiAgICBlbnZpcm9ubWVudDoKICAgICAgLSBFTkFCTEVfU1BBTUFTU0FTU0lOPTAKICAgICAgLSBFTkFCTEVfQ0xBTUFWPjAKICAgICAgLSBFTkFCTEVfRkFJTDJCQU49MAogICAgICAtIEVOQUJM RV9QT1NUR1JFWT0wCiAgICAgIC0gT05FX0RJUj0xCiAgICAgIC0gRE1TX0RFQlVHPjAKICAgICAgLSBTU0xfVFlQRT1zZWxmLXNpZ25lZAogICAgICAtIFBPU1RNQVNURVJfQUREUkVTUz1oZWxsb0BtYWlsLndnCiAgICAgIC0gT1ZFUlJJREVfSE9TVE5BTUU9bWFpbC53ZwogICAgdm9sdW1lczogCiAgICAgIC0gLi9tYWlsZGF0YTo6L3Zhci9tYWlsCiAgICAgIC0gLi9tYWlsc3RhdGU6Oi92YXIvbWFpbC1zdGF0ZQogICAgICAtIC4vbWFpbGxvZ3M6Oi92YXIvbG9nL21haWwKICAgIHBvcnRzOgogICAgICAtICIyNToyNSIKICAgICAgLSAiMTQzOjE0MyIKICAgICAgLSAiNTg3OjU4NyIKICAgICAgLSAiOTkzOjk5MyIKICAgIG5ldHdvcmtzOgogICAgICAtIG15X25ldHdvcmsKCiBuZXR3b3JrczoKICBteV9uZXR3b3JrOgogICAgZHJpdmVyOiBicmlkZ2U=" | base64 -d > docker-compose.yml

# Run Docker Compose
docker-compose up -d

# Setup WordPress sites
for i in {1..8}; do
  domain=$(shuf -zer -n6 {a..z}{A..Z}{0..9})
  docker run --name $domain --network my_network -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=root -d wordpress:latest
done

# Create email accounts
docker exec -it mail setup email add hello@mail.wg mypassword
docker exec -it mail setup email add no-reply@mail.wg mypassword

# Install Wiki.js
docker run -d --name wiki --network my_network -e DB_TYPE=mysql -e DB_HOST=mysql -e DB_PORT=3306 -e DB_USER=root -e DB_PASS=root -e DB_NAME=wiki -p 3000:3000 requarks/wiki:2

# Output
echo "Configuration complete. Your Docker containers are now running."
